# Generated by Django 4.2.5 on 2023-09-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_animation_list_app', '0002_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='recommend_text',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='recommend',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
