# Generated by Django 4.2.5 on 2023-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_animation_list_app', '0003_recommend_recommend_text_recommend_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='animate',
            name='animate_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animate',
            name='animate_photo',
            field=models.ImageField(default='oshinoko_img.jpeg', upload_to='images/'),
        ),
    ]
