# Generated by Django 4.2.5 on 2023-09-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_animation_list_app', '0004_animate_animate_description_animate_animate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animate',
            name='animate_photo',
            field=models.ImageField(default='images/oshinoko_img.jpeg', upload_to='media/images/'),
        ),
    ]
